-- ============================================================================
-- 010 · Tablas núcleo — DDL PENDIENTE DE RECUPERAR DE PRODUCCIÓN
--
-- ⛔ ESTE FICHERO NO CREA NADA TODAVÍA. NO SE PUEDE APLICAR.
--
-- Cinco tablas que la aplicación usa a diario NO tienen CREATE TABLE en
-- ningún fichero del repositorio. Existen únicamente en el proyecto Supabase
-- de producción. Sin ellas no se puede levantar un entorno desde cero:
--
--     "Base de Datos"      registro de jugadores y ratings oficiales
--     torneos              torneos
--     partidos             partidos con ratings antes/después
--     resultados_evento    resumen por jugador y torneo
--     jugadores            tabla auxiliar de jugadores (ver nota abajo)
--
-- Su DDL NO se ha inventado a propósito. Adivinar tipos, claves, defaults o
-- restricciones produciría un staging que se parece a producción sin serlo,
-- y eso es peor que no tener staging: los tests de caracterización pasarían
-- contra un esquema que no es el real.
--
-- CÓMO RELLENARLO: sigue "Extracción del esquema" en
-- docs/STAGING_RUNBOOK.md. Al terminar, sustituye este fichero por
-- 010_core_tables.sql con el DDL real y borra este PENDING.
--
-- ============================================================================
-- EVIDENCIA DE COLUMNAS (para verificar el volcado, NO para escribir el DDL)
-- ============================================================================
--
-- Lo siguiente sale de leer index.html y el SQL del repositorio (en especial
-- sql/create_api_publica.sql, que referencia columnas reales de la tabla).
-- Sirve para comprobar que el volcado de producción está completo. No es una
-- definición, y NO está garantizado que sea la lista completa.
--
-- "Base de Datos"  (PK: "Member ID" — confirmado por backup/restore_backup.mjs)
--   "Member ID"        usado como identificador en toda la app (692 usos)
--   "First Name"       nombre — NO existe una columna "Name" única; la app
--   "Last Name"        compone el nombre a partir de estas dos
--   "Escuela"          escuela/club secundario, distinto de "Club"
--   "Rating"           rating oficial vigente
--   "New Rating"       rating tras el último torneo; la app lee
--                      `p['New Rating'] || p['Rating']` (index.html:5252)
--   "Date of Birth"    TEXT con tres formatos históricos mezclados
--                      (ver fprtm_parse_fecha en 080_views.sql)
--   "Sex"              'M' / 'F'
--   "Club"             texto libre, normalizado a mano
--   "Email"            dato personal
--   "Home Address"     dato personal
--   "Expiration Date"  vencimiento de membresía, TEXT con los mismos formatos
--   photo_url          foto del jugador (bucket player-photos)
--   rating_<slug>      columnas añadidas por torneo (snapshot histórico);
--                      ver consolidar_torneo_categorias.sql
--
-- torneos  (PK: id)
--   id, nombre, fecha, publicado (add_publicado_torneos.sql),
--   deleted_at (sql/soft_delete_torneos.sql)
--
-- partidos  (PK: id)
--   torneo_id, jugador_a_id, jugador_b_id, ganador_id,
--   rating_a_antes, rating_b_antes, rating_a_despues, rating_b_despues,
--   fecha, notas, categoria (add_categoria_partidos.sql),
--   fase, ronda, grupo, orden, marcador (add_fase_ronda_partidos.sql),
--   deleted_at (sql/soft_delete_torneos.sql)
--   Escritas por subirApplyRatings() en index.html:7745-7765.
--
-- resultados_evento  (PK: id)
--   id_jugador, id_torneo, nombre, club,
--   rating_inicio, rating_fin, ganados, perdidos,
--   deleted_at (sql/soft_delete_torneos.sql)
--
-- jugadores
--   ⚠ Tabla poco clara. Aparece en la lista de backup
--   (backup/export_backup.mjs), en el trigger trg_audit_jugadores
--   (sql/create_audit_log.sql) y en varios scripts, pero index.html NO la
--   consulta en ninguna ruta activa: el registro vivo es "Base de Datos".
--   Puede ser un residuo de una migración anterior. Confirmar en producción
--   si sigue teniendo filas antes de decidir si va a staging.
--
-- ============================================================================
-- GUARDA: impide aplicar un esquema incompleto por error
-- ============================================================================

DO $$
BEGIN
  RAISE EXCEPTION
    'sql/schema/010_core_tables.PENDING.sql no contiene DDL. Recupera el esquema real de producción siguiendo docs/STAGING_RUNBOOK.md antes de aplicar sql/schema/.';
END $$;
