-- ============================================================================
-- 100 · Storage — NO ESTÁ EN ESTE REPOSITORIO
--
-- La configuración de Storage de producción (los dos buckets y las políticas
-- de `storage.objects`) se extrajo del catálogo el 2026-09-08 y **se mantiene
-- fuera de Git**, igual que el snapshot 090 de RLS.
--
-- Motivo: este repositorio es público y entre esas políticas hay una debilidad
-- de seguridad todavía abierta. Publicar la configuración exacta de un sistema
-- en uso antes de arreglarlo es un riesgo innecesario. El análisis está en el
-- informe privado de seguridad.
--
-- El fichero real es `STAGING_STORAGE.PRIVADO.sql` y se entrega por canal
-- privado junto con el 090. Reproduce, tal cual están hoy en producción:
--
--   · los dos buckets de la aplicación (`club-logos` y `player-photos`), con
--     su configuración completa;
--   · las políticas de `storage.objects` que son de la aplicación.
--
-- Lo que ese fichero NO trae, porque lo crea Supabase al provisionar el
-- proyecto y no es nuestro: el esquema `storage` en sí, sus tablas
-- (`objects`, `buckets`, `migrations`, `s3_multipart_uploads`, …), sus
-- triggers internos y sus funciones internas.
--
-- Nada de esto se puede aplicar en un Postgres normal: el esquema `storage`
-- es de Supabase. Por eso Storage está separado del resto del esquema
-- canónico y no participa en la validación local.
--
-- Lo que sí es público, porque siempre lo fue:
--   club-logos     bucket público, logos de club
--                  (lo crea `create_clubs_table.sql`, en la raíz del repo)
--   player-photos  bucket público, fotos de jugador — incluidos menores
--   backups        bucket PRIVADO, destino del backup semanal
--                  (lo crea `backup/export_backup.mjs`, no un fichero SQL)
--
-- Ver docs/SCHEMA_MANIFEST.md y docs/STAGING_RUNBOOK.md.
-- ============================================================================
